language: python
cache: pip
matrix:
  include:
  - os: linux
    python: "pypy3"
  - os: osx
    language: generic
  - os: linux
    python: "3.5"
  - os: linux
    python: "3.6"
  - os: linux
    python: "3.7"
  - os: linux
    python: "3.8"
  - os: linux
    python: "3.9-dev"
install:
  - scripts/travis.sh pip install --requirement=requirements-travis.txt
  - scripts/travis.sh LC_ALL=C pip install .
# The `make test' command below is run under `sudo -E' to enable
# the test suite to read /var/log/syslog on Travis CI workers.
script:
  - scripts/travis.sh make check
  - scripts/travis.sh sudo -E make test
after_success:
  - scripts/travis.sh coveralls
branches:
  except:
    - /^[0-9]/
